### ISSUE TITLE
Script tag at top of the body???

### ISSUE THREAD

**Issue by rymatech** [FAC-Sixteen/Week-1-project-JASH#23]
I have been taught to put the script tag just before the bottom body tag, is there a reason you have done it different?

**Comment by boi87** [comment]
True that!
Why is it better to put the script tag at the bottom of the page?

**Comment by jameslevine** [comment]
Thanks for pointing this issue. It actually happened because we created the html template and it inserted a script tag with a default script.js filename.

I have now removed this script tag entirely since we made it without Javascript!!

Thank you Ryan!
